### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by Zyles** [helderco/docker-php-5.3#1]
Hey. I really really need to run a legacy app in 5.3 and this is the only package I could find but I am having some issues. Maybe you know what is wrong...

I have Nginx and simple index.php with phpinfo() file in `/home/httpd/myapp/public/index.php`

I created a config for it with `fastcgi_pass 127.0.0.1:9001;`

Started docker with:

```
sudo docker run -d -it -p 9001:9000 --name legacy_app -v /home/httpd/myapp/public":/var/www/html helder/php-5.3
```

When I visit the URL however I get "File not found."

Thanks.

**Comment by helderco** [comment]
Hi. Can I see your nginx vhost?

Also confirm that the double quote you left alone in the volume option was a mistake.

**Comment by Zyles** [comment]
Yes sorry there is no quote. Not sure how that got there.

Here is the vhost:

```
server {
        server_name myapp.example.com;
        root /home/httpd/myapp/public;
        error_log /var/log/nginx/myapp.example.com.error.log info;

        location / {
                try_files $uri /index.php$is_args$args;
        }

        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_pass 127.0.0.1:9001;
                fastcgi_index index.php;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_nam$
        }
}
```

**Comment by helderco** [comment]
Your nginx root doesn't match what's in the container so PHP-FPM can't find the path you're sending.

The PHP container doesn't need to read from `/var/www/html`, so you can have the same path:

```
sudo docker run -d -it -p 9001:9000 --name legacy_app -v /home/httpd/myapp/public:/home/httpd/myapp/public helder/php-5.3
```

**Comment by Zyles** [comment]
Thanks man. Much appreciated.
