### ISSUE TITLE
Add extensions

### ISSUE THREAD

**Issue by Zyles** [helderco/docker-php-5.3#2]
Hey again.

Is it possible to add new extensions? If so how?

For example I need the php_soap.dll enabled. It is not enabled by default.

**Comment by helderco** [comment]
Yes, it's the same as the official images: https://github.com/docker-library/docs/tree/master/php#how-to-install-more-php-extensions

**Comment by helderco** [comment]
Specifically for Soap, you need the libxml2 package:

```
FROM helder/php-5.3

RUN apt-get update \
 && apt-get install libxml2-dev --no-install-recommends -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && docker-php-ext-install soap
```

**Comment by Zyles** [comment]
Thanks.
